package com.softwaremine.dps.ai.intent

import com.softwaremine.dps.domain.intent.DpsIntent
import com.softwaremine.dps.domain.intent.IntentType
import com.softwaremine.dps.domain.permission.DpsPermission
import com.softwaremine.dps.domain.tool.ToolResult

/**
 * Turns a [ToolResult] into something a person would say.
 *
 * ## Purpose
 * The last stage of the pipeline. Tool results are structured; users want
 * sentences.
 *
 * ## Why this is templated rather than generated by the model
 * The obvious design is to hand the `ToolResult` back to the LLM and ask it to
 * phrase a reply. That was rejected for two reasons, and the second is the
 * important one.
 *
 * **Latency.** A second inference pass costs 5–15 s on this hardware
 * (`docs/PERFORMANCE-DAY-04.md`). Doubling the wait to rephrase text DPS
 * already knows is a poor trade.
 *
 * **Safety.** A language model asked to describe a result *will* eventually
 * describe it wrongly. The specific failure that matters: a model handed the
 * outcome of `PrepareWhatsAppMessageTool` writing **"I've sent your message to
 * Abdul"** — when nothing was sent, and the whole confirmation design exists to
 * guarantee the user presses send themselves.
 *
 * Phase C made sending structurally impossible. Letting a model narrate the
 * result would reintroduce the same lie at the last step, where it is least
 * likely to be noticed. Templating removes that possibility entirely: the
 * wording is written once, reviewed, and cannot drift.
 *
 * Where genuine conversational range is wanted — ordinary chat — the model
 * still writes freely. It simply does not get to report on actions.
 *
 * ## AI Rules 1 and 2
 * No output here names a tool, an operation, an Android permission string, or
 * an exception. `ToolResult.Error.cause` is deliberately never surfaced.
 *
 * ## Dependencies
 * Domain intent, permission and tool types. Pure Kotlin.
 */
class ToolResponseGenerator {

    /**
     * Phrases [result] for the user.
     *
     * @param intent what they asked for, used to keep wording specific.
     */
    fun describe(result: ToolResult, intent: DpsIntent): String = when (result) {
        is ToolResult.Success -> result.summary.ifBlank { defaultSuccess(intent.type) }

        is ToolResult.Failure -> phraseFailure(result, intent)

        is ToolResult.PermissionRequired -> phrasePermission(result, intent)

        is ToolResult.Cancelled -> "Alright, I've stopped that."

        is ToolResult.Unsupported -> phraseUnsupported(result, intent)

        is ToolResult.Timeout ->
            "That took longer than expected, so I stopped waiting. Shall I try again?"

        is ToolResult.Error ->
            // Never surfaces result.cause. It carries an exception class and
            // message, which tells the user nothing they can act on and exposes
            // internals AI Rules 1 and 2 forbid showing.
            "Something went wrong on my side and I couldn't finish that. " +
                "Could you try again?"
    }

    /**
     * Failures are the tool working and the operation not succeeding — the
     * reason is written for a user and is safe to pass through.
     */
    private fun phraseFailure(result: ToolResult.Failure, intent: DpsIntent): String {
        val reason = result.reason.trim().ifEmpty { "I couldn't do that." }
        return if (result.retryable) "$reason Shall I try again?" else reason
    }

    /**
     * Explains what is needed and why, in the user's terms.
     *
     * The rationale names the *capability*, never the permission constant. And
     * DPS asks — it never opens a settings screen unprompted, because sending
     * someone out of the app is a visible action requiring their consent.
     */
    private fun phrasePermission(
        result: ToolResult.PermissionRequired,
        intent: DpsIntent,
    ): String {
        val need = when {
            result.permissions.contains(DpsPermission.READ_CONTACTS) -> "your contacts"
            result.permissions.any {
                it == DpsPermission.READ_CALENDAR || it == DpsPermission.WRITE_CALENDAR
            } -> "your calendar"
            result.permissions.contains(DpsPermission.POST_NOTIFICATIONS) -> "notifications"
            result.permissions.contains(DpsPermission.SCHEDULE_EXACT_ALARM) -> "exact alarms"
            else -> "a permission"
        }

        val purpose = when (intent.type) {
            IntentType.REMINDER -> "set that reminder"
            IntentType.CALENDAR_EVENT -> "add that to your calendar"
            IntentType.NOTIFICATION -> "show you that"
            IntentType.CONTACT_LOOKUP -> "look that person up"
            IntentType.WHATSAPP_MESSAGE -> "find who you meant"
            IntentType.EMAIL_MESSAGE -> "find their address"
            IntentType.CALL_CONTACT -> "find who you meant"
            // Day 06 tools declare no required permissions — unreachable in
            // practice, but every case must say something.
            IntentType.TASK -> "manage that task"
            IntentType.WORK_LOG -> "log that"
            IntentType.MEETING_NOTE -> "save that note"
            IntentType.ACTION_ITEM -> "track that"
            IntentType.REPORT -> "build that report"
            IntentType.CONVERSATION -> "do that"
        }

        return "I need access to $need before I can $purpose. " +
            "Would you like to allow it? I'll pick up where we left off."
    }

    private fun phraseUnsupported(result: ToolResult.Unsupported, intent: DpsIntent): String {
        val base = result.reason.trim().ifEmpty { "I can't do that on this device." }
        return if (result.minApiLevel != null) {
            "$base It needs a newer version of Android than this phone has."
        } else {
            base
        }
    }

    /** Fallback when a tool succeeds without a summary. Should be rare. */
    private fun defaultSuccess(type: IntentType): String = when (type) {
        IntentType.REMINDER -> "Reminder set."
        IntentType.CALENDAR_EVENT -> "Added to your calendar."
        IntentType.NOTIFICATION -> "Done."
        IntentType.CONTACT_LOOKUP -> "Here's what I found."
        IntentType.WHATSAPP_MESSAGE -> "Your message is ready to send."
        IntentType.EMAIL_MESSAGE -> "Your email is ready to send."
        IntentType.CALL_CONTACT -> "The dialer is open."
        IntentType.TASK -> "Done."
        IntentType.WORK_LOG -> "Logged."
        IntentType.MEETING_NOTE -> "Saved."
        IntentType.ACTION_ITEM -> "Done."
        IntentType.REPORT -> "Here you go."
        IntentType.CONVERSATION -> "Done."
    }
}
